name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d --build

      - name: Run tests
        run: docker compose exec -T app pytest

      - name: Stop containers
        if: always()
        run: docker compose down -v